I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/Ch02/Ch02.rpy", line 11, in script
    paly amb "amb_office.mp3"
Exception: Sayer 'paly' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/Ch02/Ch02.rpy", line 11, in script
    paly amb "amb_office.mp3"
  File "/Users/joooyeon/Documents/renpy-8.3.7-sdk/renpy/ast.py", line 2586, in execute
    Say.execute(self)
  File "/Users/joooyeon/Documents/renpy-8.3.7-sdk/renpy/ast.py", line 583, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Users/joooyeon/Documents/renpy-8.3.7-sdk/renpy/ast.py", line 472, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'paly' is not defined.

macOS-13.6.4-arm64-arm-64bit arm64
Ren'Py 8.3.7.25031702
MysteryGame 1.0
Mon Jun  9 07:09:51 2025
