I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/Ch03.rpy", line 201, in script
    with punch
  File "game/scripts/Ch03.rpy", line 201, in <module>
    with punch
NameError: name 'punch' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/Ch03.rpy", line 201, in script
    with punch
  File "/Users/joooyeon/Documents/renpy-8.3.7-sdk/renpy/ast.py", line 1367, in execute
    trans = renpy.python.py_eval(self.expr)
  File "/Users/joooyeon/Documents/renpy-8.3.7-sdk/renpy/python.py", line 1218, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/Users/joooyeon/Documents/renpy-8.3.7-sdk/renpy/python.py", line 1211, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/scripts/Ch03.rpy", line 201, in <module>
    with punch
NameError: name 'punch' is not defined

macOS-13.6.4-arm64-arm-64bit arm64
Ren'Py 8.3.7.25031702
MysteryGame 1.0
Mon Jun  9 17:44:45 2025
